#
#	Makefile for all codes
#
#
all:
	cd aseriesCMB && make && cd ..
	cd Check_HY   && make && cd ..
	cd demult     && make && cd ..
	cd GenTopo    && make && cd ..
	cd Kirchhoff  && make && cd ..
	cd line2point && make && cd ..
	cd PSVHY      && make && cd ..
clean:
	cd aseriesCMB && make clean && cd ..
	cd Check_HY   && make clean && cd ..
	cd demult     && make clean && cd ..
	cd GenTopo    && make clean && cd ..
	cd Kirchhoff  && make clean && cd ..
	cd line2point && make clean && cd ..
	cd PSVHY      && make clean && cd ..
